version: '3'
services:
  # nodejs-server:
  #   build:
  #     context: ./api
  #   ports:
  #     - "3080:3080"
  #   container_name: node-grc
  #   volumes:
  #      - ./api:/usr/src/app/api
  #      - /usr/src/app/api/node_modules
  react-docker:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: react-docker
    stdin_open: true
    volumes:
       - ./:/var/www/html/app
       - /var/www/html/app/node_modules